name: vost
description: Aplicação para VOST

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 0.1.3

  sensors: 0.4.1+7
  pull_to_refresh: 1.5.8
  flutter_page_indicator: 0.0.3

  #map
  flutter_map: 0.8.2

  #testing
  # test: 1.11.0
  mockito:  4.1.1

  #built_value
  built_collection: 4.3.2
  built_value: 7.0.8

  #core
  rxdart: 0.23.1
  shared_preferences: 0.5.6
  stream_disposable: 0.1.0
  firebase_core: 0.4.3+2

  # Network
  dio: 3.0.8
  http: 0.12.0+4

  #localizations
  intl: 0.16.1
  intl_translation: 0.17.9

  # UI
  flare_flutter: 2.0.1

  #Navigation
  url_launcher: 5.4.1

  #permissions
  notification_permissions: 0.4.3
  location_permissions: 2.0.4+1

dev_dependencies:
  build_runner: 1.7.3
  built_value_generator: 7.0.8
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/flare/vost_logo.flr
    - assets/data/contributors.json
    - assets/images/
